### ISSUE TITLE
Whitespaces in Redis config for TLS clusters

### ISSUE THREAD

**Issue by tbumke** [NETWAYS/ansible-role-redis-cluster#12]
If the installation scenario is `cluster` and TLS cluster is enabled, the Redis config has unneeded whitespaces due to the indentation of the Jinja2 if-clauses, e.g.:

``` jinja2
{% if item.redis_tls_port is defined %}
...
tls-auth-clients {{ item.redis_tls_auth_clients }}
  {% if redis_installation_scenario == 'cluster' and item.redis_tls_cluster is defined %}
tls-cluster {{ item.redis_tls_cluster }}
  {% endif %}
  {% if item.redis_tls_replication is defined %}
tls-replication {{ item.redis_tls_replication }}
  {% endif %}
...
{% endif %}
```

Will be rendered to:

``` text
tls-auth-clients no
  tls-cluster yes
    tls-replication yes
```

The nested if-clause should use some Jinja2 [whitespace control](https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control) to remove the preceding whitespaces.

It is worth mentioning, that Jinja2's whitespace control works very differently depending on the Ansible version used on the control node. With Ansible minimum version set to "2.4", it might be a better option to remove the preceding whitespaces from the template (at the cost of losing some structure).

**Comment by martialblog** [comment]
Fixex in #13
