### ISSUE TITLE
Print cluster info should only display command output

### ISSUE THREAD

**Issue by tbumke** [NETWAYS/ansible-role-redis-cluster#6]
Task `Print cluster info` in `cluster.yml` prints out the entire registered var instead of, for example, just the `stdout_lines`. This exposes the cluster password which is passed on the command-line.

https://github.com/NETWAYS/ansible-role-redis-cluster/blob/9ebbad2cb900515eac7fac09550f432d9a969190/tasks/cluster.yml#L44

**Comment by tbumke** [comment]
@afeefghannam89 I have prepared a fix. If you'd allow me to push to this repo I can open a PR.

**Comment by martialblog** [comment]
@tbumke You can create a fork and open a PR anytime. We will review it then
